---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cert-manager-controller
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: cert-manager
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: cert-manager
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: cert-manager
  egress:
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: webhook
    toPorts: [{ports: [{port: "10250"}]}]
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: cert-manager-webhook
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: webhook
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: cert-manager
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: webhook
      app.kubernetes.io/component: webhook
      app.kubernetes.io/instance: cert-manager
  ingress:
  - fromEntities: [kube-apiserver, cluster]
    toPorts: [{ports: [{port: "10250"}]}]
  - fromEndpoints:
    - matchLabels:
        app.kubernetes.io/name: netutils
    toPorts: [{ports: [{port: "10250"}]}]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-externaldns-webhook
  labels:
    app.kubernetes.io/name: cert-manager-externaldns-webhook
rules:
- apiGroups: [cluster.local]
  resources: [cert-manager-externaldns-webhook]
  verbs: [get, list, watch, update, create, delete]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager:externaldns-webhook
  labels:
    app.kubernetes.io/name: cert-manager-externaldns-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-externaldns-webhook
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager
  namespace: cert-manager
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}
---
# Letsencrypt staging issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        webhook:
          groupName: cluster.local
          solverName: cert-manager-externaldns-webhook
---
# Letsencrypt production issuer
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        webhook:
          groupName: cluster.local
          solverName: cert-manager-externaldns-webhook
