---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: cert-manager
  name: cert-manager-externaldns-webhook-ca
  labels:
    app.kubernetes.io/name: cert-manager-externaldns-webhook
spec:
  secretName: cert-manager-externaldns-webhook-ca-cert
  commonName: ca.cert-manager-externaldns-webhook.cert-manager
  duration: 87600h
  isCA: true
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: selfsigned
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  namespace: cert-manager
  name: cert-manager-externaldns-webhook
  labels:
    app.kubernetes.io/name: cert-manager-externaldns-webhook
spec:
  ca:
    secretName: cert-manager-externaldns-webhook-ca-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  namespace: cert-manager
  name: cert-manager-externaldns-webhook
  labels:
    app.kubernetes.io/name: cert-manager-externaldns-webhook
spec:
  secretName: cert-manager-externaldns-webhook-tls
  duration: 87600h
  issuerRef:
    name: cert-manager-externaldns-webhook
  dnsNames:
  - cert-manager-externaldns-webhook
  - cert-manager-externaldns-webhook.cert-manager
  - cert-manager-externaldns-webhook.cert-manager.svc
  - cert-manager-externaldns-webhook.cert-manager.svc.cluster.local
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cert-manager
  name: cert-manager-externaldns-webhook
  labels:
    app.kubernetes.io/name: cert-manager-externaldns-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: kube-system
  name: cert-manager-externaldns-webhook:webhook-authentication-reader
  labels:
    app.kubernetes.io/name: cert-manager-externaldns-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager-externaldns-webhook
  namespace: cert-manager
---
# apiserver gets the auth-delegator role to delegate auth decisions to
# the core apiserver
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-externaldns-webhook:auth-delegator
  labels:
    app.kubernetes.io/name: cert-manager-externaldns-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager-externaldns-webhook
  namespace: cert-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-externaldns-webhook
  labels:
    app.kubernetes.io/name: cert-manager-externaldns-webhook
rules:
- apiGroups: [externaldns.k8s.io]
  resources: [dnsendpoints]
  verbs: [list, create, delete]
- apiGroups: [flowcontrol.apiserver.k8s.io]
  resources: [flowschemas, prioritylevelconfigurations]
  verbs: [list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-manager-externaldns-webhook:flowcontrol
  labels:
    app.kubernetes.io/name: cert-manager-externaldns-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-externaldns-webhook
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: cert-manager-externaldns-webhook
  namespace: cert-manager
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.cluster.local
  labels:
    app.kubernetes.io/name: cert-manager-externaldns-webhook
  annotations:
    cert-manager.io/inject-ca-from: cert-manager/cert-manager-externaldns-webhook
spec:
  group: cluster.local
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: cert-manager-externaldns-webhook
    namespace: cert-manager
  version: v1alpha1
